# Generated by Django 6.6 on 2023-06-06 13:24
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno hrace musí být vyplněno'},
                                           help_text='Zadejte jméno hrace', max_length=80, verbose_name='Jméno hrace')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení autora musí být vyplněno'},
                                              help_text='Zadejte příjmení autora', max_length=50,
                                              verbose_name='Příjmení hrace')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('fotografie', models.ImageField(upload_to='hraci', verbose_name='Fotografie')),
            ],
            options={
                'verbose_name': 'Hrac',
                'verbose_name_plural': 'Hraci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Soutez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('druh', models.CharField(error_messages={'blank': 'Název vydavatelství je povinný údaj'},
                                          help_text='Zadejte název vydavatelství', max_length=100,
                                          verbose_name='Název vydavatelství')),
            ],
            options={
                'verbose_name': 'Soutez',
                'verbose_name_plural': 'Soutez',
                'ordering': ['druh'],
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno autora musí být vyplněno'},
                                           help_text='Zadejte jméno autora', max_length=80,
                                           verbose_name='Jméno autora')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení autora musí být vyplněno'},
                                              help_text='Zadejte příjmení autora', max_length=50,
                                              verbose_name='Příjmení autora')),
                ('narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('fotografie', models.ImageField(upload_to='hraci', verbose_name='Fotografie')),
            ],
            options={
                'verbose_name': 'Trener',
                'verbose_name_plural': 'Treneri',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Titul knihy musí být vyplněn'},
                                           help_text='Zadejte titul knihy', max_length=100,
                                           verbose_name='Titul knihy')),
                ('Soutezi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='myapp.soutez', verbose_name='Soutez')),
                ('Treneri', models.ManyToManyField(to='myapp.trener')),
                ('hraci', models.ManyToManyField(to='myapp.hrac')),
            ],
            options={
                'verbose_name': 'Tym',
                'verbose_name_plural': 'Tymy',
                'ordering': ['nazev'],
            })



    ]
